version: "3.9"
services:
  http_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    environment:
      - FILE_PATH=/app/files/
  proxy:
    build:
      context: .
      dockerfile: Dockerfile-Proxy
    ports:
      - "81:8081"
    environment:
      - SERVER_IP=http_server
      - SERVER_PORT=8080
